# Generated by Django 3.1.3 on 2020-12-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='skin',
        ),
    ]
